#include "rick_roll.h"

const wchar_t *rick_roll = L"We're no strangers to love\n"
	L"You know the rules and so do I\n"
	L"A full commitment's what I'm thinking of\n"
	L"You wouldn't get this from any other guy\n"
	L"I just wanna tell you how I'm feeling\n"
	L"Gotta make you understand\n"
	L"Never gonna give you up\n"
	L"Never gonna let you down\n"
	L"Never gonna run around and desert you\n"
	L"Never gonna make you cry\n"
	L"Never gonna say goodbye\n"
	L"Never gonna tell a lie and hurt you\n"
	L"We've known each other for so long\n"
	L"Your heart's been aching but you're too shy to say it\n"
	L"Inside we both know what's been going on\n"
	L"We know the game and we're gonna play it\n"
	L"And if you ask me how I'm feeling\n"
	L"Don't tell me you're too blind to see\n"
	L"Never gonna give you up\n"
	L"Never gonna let you down\n"
	L"Never gonna run around and desert you\n"
	L"Never gonna make you cry\n"
	L"Never gonna say goodbye\n"
	L"Never gonna tell a lie and hurt you\n"
	L"Never gonna give you up\n"
	L"Never gonna let you down\n"
	L"Never gonna run around and desert you\n"
	L"Never gonna make you cry\n"
	L"Never gonna say goodbye\n"
	L"Never gonna tell a lie and hurt you\n"
	L"Never gonna give, never gonna give\n"
	L"(Give you up)\n"
	L"(Ooh)Never gonna give, never gonna give\n"
	L"(Give you up)\n"
	L"We've known each other for so long\n"
	L"Your heart's been aching but you're too shy to say it\n"
	L"Inside we both know what's been going on\n"
	L"We know the game and we're gonna play it\n"
	L"I just wanna tell you how I'm feeling\n"
	L"Gotta make you understand\n"
	L"Never gonna give you up\n"
	L"Never gonna let you down\n"
	L"Never gonna run around and desert you\n"
	L"Never gonna make you cry\n"
	L"Never gonna say goodbye\n"
	L"Never gonna tell a lie and hurt you\n"
	L"Never gonna give you up\n"
	L"Never gonna let you down\n"
	L"Never gonna run around and desert you\n"
	L"Never gonna make you cry\n"
	L"Never gonna say goodbye\n"
	L"Never gonna tell a lie and hurt you\n"
	L"Never gonna give you up\n"
	L"Never gonna let you down\n"
	L"Never gonna run around and desert you\n"
	L"Never gonna make you cry\n";